spring:
  application:
    name: user-service
  profiles:
    default: local

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      probes:
        enabled: true   # /actuator/health/liveness и /readiness — пригодятся для Docker и облака